sudo: false
language: scala
dist: trusty

stages:
  - name: test

scala_version_211: &scala_version_211 2.11.12
scala_version_212: &scala_version_212 2.12.8
scala_version_213: &scala_version_213 2.13.0

java_8: &java_8 openjdk8
java_11: &java_11 openjdk11

jobs:
  include:
    - &tests
      env: TEST="test"
      before_install:
        - export PATH=${PATH}:./vendor/bundle
      addons:
        postgresql: "9.4"
        apt:
          packages:
            - postgresql-9.4-postgis-2.3 # This might not be necessary in the future. If the Travis people update the trusty env to include this package whenever it sees pg getting installed then this can go away.
      install:
        - rvm use 2.4 --install --fuzzy
        - gem update --system
        - gem install sass
        - gem install jekyll -v 3.2.1
      before_script:
        - project/travis-before-build.sh
      script:
        - sbt ++$TRAVIS_SCALA_VERSION test
        - sbt ++$TRAVIS_SCALA_VERSION mimaReportBinaryIssues
      scala: *scala_version_211
      jdk: *java_8
    - <<: *tests
      scala: *scala_version_212
      jdk: *java_8
      script:
        - sbt ++$TRAVIS_SCALA_VERSION test
        - sbt ++$TRAVIS_SCALA_VERSION mimaReportBinaryIssues
        - sbt ++$TRAVIS_SCALA_VERSION -J-XX:+UseG1GC docs/tutQuick
    - <<: *tests
      scala: *scala_version_213
      jdk: *java_8
      script:
        - sbt ++$TRAVIS_SCALA_VERSION thirteen/test
        #- sbt ++$TRAVIS_SCALA_VERSION thirteen/mimaReportBinaryIssues
    - <<: *tests
      scala: *scala_version_212
      jdk: *java_11
    - <<: *tests
      scala: *scala_version_213
      jdk: *java_11
      script:
        - sbt ++$TRAVIS_SCALA_VERSION thirteen/test
        #- sbt ++$TRAVIS_SCALA_VERSION thirteen/mimaReportBinaryIssues

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0d4c1d733e9259a3db54
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

cache:
  directories:
  - $HOME/.sbt/1.0
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/cache
  - $HOME/.sbt/launchers
  - $HOME/.ivy2
  - $HOME/.coursier
  - $HOME/.rvm/
  - vendor/bundle

before_cache:
  - du -h -d 1 $HOME/.ivy2/
  - du -h -d 2 $HOME/.sbt/
  - du -h -d 4 $HOME/.coursier/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.coursier/cache -name "*.lock" -type f -delete
