name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 13
        uses: olafurpg/setup-scala@v10
        with:
          java-version: 13
      - name: Cache SBT
        uses: coursier/cache-action@v3
      - name: Start up Postgres
        run: docker-compose up -d
      - name: Run tests
        run: csbt headerCheck compile test:compile test
      - name: Shut down Postgres
        run: docker-compose down
